const credentials = require("../config/mailCredentials");
const nodemailer = require("nodemailer");
const moment = require("moment-timezone");
const Subscriber = require('../models/Subscriber.js');

const dispatcher = async ({
emailBody,
sendAt
}) => {
  moment.utc(sendAt).tz("Europe/Copenhagen");
  

let transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    pool: true,
    secure: true, // use SSL
    auth: {
        user: credentials.user,
        pass: credentials.pass
    }

});


  // verify connection configuration
   await transporter.verify();
  console.log("email account ready");

  

   var subscribers = await Subscriber.query().select('email');

  let mailingList = [];

  subscribers.forEach(id => {
        mailingList.push(id.email)
  });

 

  console.log(subscribers);

  var mailOptions = {
    
      from: credentials.user,  //`${email} `, // list of receivers
      to: mailingList,
      subject: "Adolphine - New reminder delivered",
      html: `
             <p>Dear SimCorper</p>
             
             <p>Here is something worth remembering for you</p>
  
             <h1>Reminder: ${emailBody}</h1>
            
             <p>Best regards,<br>
             Adolphine<br>
             <p><input type="text" value="Above message is autogenerated." disabled /> </p>`,
    };


    transporter.sendMail(mailOptions, (error) => {
      if (error) {
          console.log(error)
          return
      }
      console.log("Sent!")
  });
  };


module.exports = dispatcher;