const credentials = require("../config/mailCredentials");
const nodemailer = require("nodemailer");
const moment = require("moment-timezone");

const dispatcher = async ({
emailBody,
sendAt
}) => {
  moment.utc(sendAt).tz("Europe/Copenhagen");
  

let transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    pool: true,
    secure: true, // use SSL
    auth: {
        user: credentials.user,
        pass: credentials.pass
    }

});


  // verify connection configuration
   await transporter.verify();
  console.log("email account ready");

  // get emails from database
//var mailingList =["anna.maria.wilczek@gmail.com", "anna.wilczek@student.uw.edu.pl", "anwi@simcorp.com" ];
 //mailingList.toString();
  
  const concatEmail = "anna.maria.wilczek@gmail.com";  //username.concat("@simcorp.com");
 // email ="anna.maria.wilczek@gmail.com";

 
  

   var subscribers = [  async () => {
    await Subscriber.query().select();
  }];

  subscribers.toString();

  var mailOptions = {
    
      from: credentials.user,  //`${email} `, // list of receivers
      to: concatEmail,
      subject: "Adolphine - New reminder delivered",
      html: `
             <p>Dear SimCorper</p>
             
             <p>Here is something worth remembering for you</p>
  
             <h1>Reminder: ${emailBody}</h1>
            
             <p>Best regards,<br>
             Adolphine<br>
             <p><input type="text" value="Above message is autogenerated." disabled /> </p>`,
    };


    transporter.sendMail(mailOptions, (error, data) => {
      if (error) {
          console.log(error)
          return
      }
      console.log("Sent!")
  });
  };


module.exports = dispatcher;